baseURL = 'http://localhost/'
languageCode = 'es'
defaultContentLanguage = "es"
title = 'Recetas'
headerTitle = 'Recetas'
theme = 'dream'

[params]
  background = "#f7f7f7"
  # backgroundImage = "/img/default1.jpg"
  linkColor = "seagreen"

  # dark mode
  #defaultDark = true
  #backgroundDark = "black"
  #backgroundImageDark = "/img/background-dark.jpg"
  #darkLinkColor = "darkseagreen"
  #darkNav = true
  #dark404 = true

  author = "Antonio Cintora Romero"
  # description = ""
  # avatar = "/img/avatar.jpeg"
  headerTitle = "Recetas Thermomix"
  motto = "Mi blog de recetas"
  maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  email = "tonicintora@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2022

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  reversePostAndAside = true
  # shareInAside = true
  fixedNav = true
  collapsibleTags = true
  collapseBySummary = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJSBefore = []
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"